#
#Copyright Odin Solutions S.L. All Rights Reserved.
#
#SPDX-License-Identifier: Apache-2.0
#

version: '3.1'

services:
  apicapabilitymanager:
    image: iotcrawler/capability-manager
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
        - "3030:3030"
    restart: unless-stopped
    environment:
        - keyrock_protocol=https
        - keyrock_host=155.54.95.170
        - keyrock_port=443

        - PDP_URL=155.54.95.170
        - PDP_port=8080
