#
#Copyright Odin Solutions S.L. All Rights Reserved.
#
#SPDX-License-Identifier: Apache-2.0
#

version: '3.1'

services:
  apicapabilitymanager:
    image: iotcrawler/capability-manager
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
        - "3030:3030"
    restart: unless-stopped
    environment:
        - keyrock_protocol=https
        - keyrock_host=<specify IdM Public IP address>
        - keyrock_port=443

        # PDP_URL format: https://<XACML-PDP-IP>:<XACML-PDP-PORT><XACML-PDP-SERVICE>
        - PDP_URL=<specify XACML-PDP Public address (including service)>